# Generated by Django 4.0.4 on 2022-06-07 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Duser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Duser.opsuser')),
            ],
        ),
    ]
